### PR TITLE
Markup and styling for enewsletter signup banner.

### PR DESCRIPTION
**Pull request by Wilto**
j5-banner

### CODE REVIEW

**Comment by tkellen** [comment]
Thank you @Wilto 

/cc @reconbot and @gregorspamsa for any additional change requests. This is in your court now.

**Comment by gregorspamsa** [comment]
Thank you, @Wilto and @tkellen! @reconbot, can you send me updated copy for the short description before the subscribe form?

**Comment by gregorspamsa** [comment]
Thanks so much, @reconbot. Let's go with:

>Hi! The Johnny-Five community is building new projects every day. We made this newsletter to tell you about what's new, what's good, and what's next for Open Source robotics. Join us in exploring what we can make together. 

Once we have the copy updated, it's good to go, and I will move forward with creating tracking links.

**Comment by gregorspamsa** [comment]
Howdy! @reconbot and @tkellen, what would be the best way to update the copy and deploy the new site?

**Comment by tkellen** [comment]
@gregorspamsa you'll have to clone this repo, check out this branch, edit the content, make a commit and push it up

**Comment by gregorspamsa** [comment]
This has been pushed into production, so will close this. Thanks everyone for your help!

**Pull request merged**
