### PR TITLE
adding Facebook og: tags

### LINKED ISSUE #45: Set og:* properties for Facebook sharing
The default shared image for Facebook is one of the specific boards. We should add meta properties to point to a more reasonable (logo? Johnny-Five drawing?) suggestion.

Here is Facebook's debugger output for the website:
https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fjohnny-five.io

Not explicitly listed at that link, the preview image must be a minimum of 200x200.

### PR DESCRIPTION
**Pull request by pierceray**
I think this is a start for the og:* tags.  There isn't an appropriately sized image for the og:image in the repo currently but this can be added.

Fixes #45

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM. Let's see what @isaacdurazo says about this: https://github.com/bocoup/johnny-five.io/issues/45#issuecomment-106902514

**Comment by pierceray** [comment]
I added the og:image tag, they have to be absolute url's.  Tested on a temp site and the Facebook object debugger worked as expected.  So I guess this is good to go now.

**Comment by Resseguie** [comment]
@rwaldron is there a way to auto-insert the absolute URL via your templates? That would probably make this more robust to future change?

**Comment by pierceray** [comment]
I think it "might" make it more robust, but it would likely only be applicable if we were going to be mirroring the site at a different url.  Even then you would want one url to be canonical.  I can make the change if we really think it is needed, but I think it is just adding complexity for complexity's sake.

**Comment by Resseguie** [comment]
Ok. LGTM then, @rwaldron. Thanks @pierceray

**Comment by Resseguie** [comment]
@rwaldron let me know when a new version goes live and I can do a sanity check that it behaves as espected sharing on various social sites.

**Comment by rwaldron** [comment]
I pushed the site today :)

**Comment by Resseguie** [comment]
Cool, and confirmed it popped up with the expected image just not on Facebook. Thanks @pierceray. This will be a lot better when sharing links.

**Pull request merged**
